export const fallbackOpportunities = [
  {
    title: "SDE Intern",
    organization: "Amazon India",
    org: "Amazon India",
    type: "internship",
    matchScore: 95,
    description: "Amazon is looking for software development engineering interns. Work on cloud computing, distributed systems, and e-commerce scale problems.",
    url: "https://amazon.jobs",
    apply_link: "https://amazon.jobs",
    source: "amazon",
    deadline: "2026-06-01",
    daysLeft: 20,
    tags: ["software engineering", "java", "aws", "backend"],
    matchReason: "Strong match for coding skills and degree."
  },
  {
    title: "Smart India Hackathon 2026",
    organization: "Ministry of Education",
    org: "Ministry of Education",
    type: "hackathon",
    matchScore: 92,
    description: "Nationwide initiative to provide students a platform to solve some of the pressing problems we face in our daily lives.",
    url: "https://sih.gov.in",
    apply_link: "https://sih.gov.in",
    source: "sih",
    deadline: "2026-07-15",
    daysLeft: 60,
    tags: ["hackathon", "innovation", "problem solving", "nation building"],
    matchReason: "Great opportunity to build impactful projects."
  },
  {
    title: "Google Summer of Code",
    organization: "Google",
    org: "Google",
    type: "open source",
    matchScore: 98,
    description: "Global, online program focused on bringing new contributors into open source software development.",
    url: "https://summerofcode.withgoogle.com/",
    apply_link: "https://summerofcode.withgoogle.com/",
    source: "gsoc",
    deadline: "2026-03-31",
    daysLeft: 14,
    tags: ["open source", "mentorship", "development", "remote"],
    matchReason: "Matches your goal of contributing to open source."
  },
  {
    title: "Pragati Scholarship",
    organization: "AICTE",
    org: "AICTE",
    type: "scholarship",
    matchScore: 85,
    description: "Assistance to girls pursuing technical education. Scholarship amount of Rs. 50,000 per annum.",
    url: "https://www.aicte-india.org/schemes/students-development-schemes",
    apply_link: "https://www.aicte-india.org/schemes/students-development-schemes",
    source: "aicte",
    deadline: "2026-08-30",
    daysLeft: 90,
    tags: ["scholarship", "women in tech", "financial aid", "engineering"],
    matchReason: "Applicable scheme based on broad student profile."
  },
  {
    title: "Data Science Remote Internship",
    organization: "TCS iON",
    org: "TCS iON",
    type: "internship",
    matchScore: 88,
    description: "Explore the world of data with practical, remote projects guided by TCS experts.",
    url: "https://learning.tcsionhub.in",
    apply_link: "https://learning.tcsionhub.in",
    source: "tcs ion",
    deadline: "2026-06-15",
    daysLeft: 35,
    tags: ["data science", "python", "machine learning", "analytics"],
    matchReason: "Relevant for data engineering and analytics interests."
  }
];
